### ISSUE TITLE
Sobre los datos utilizados.

### ISSUE THREAD

**Issue by carranco-sga** [mexicovid19/Mexico#28]
Hola a todos,

Muchas gracias por difundir información tan relevante para el presente de una manera amigable.
Descargando los datos de su página, noté que citan varias fuentes, lo que me parece excelente.

Les escribo para comentarles que he estado compilando los datos diarios publicados por la Secretaría de Salud federal en [este repositorio](https://github.com/carranco-sga/Mexico-COVID-19), por si quisieran agregar otra fuente de información.

De nuevo, muchas gracias, saludos,
Gabriel Carranco.

**Comment by LeonardoCastro** [comment]
Hola Gabriel, 

Tu repositorio fue citado en el README de nuestro repositorio fuente [https://github.com/mexicovid19/Mexico-datos](https://github.com/mexicovid19/Mexico-datos). Esperamos colaborar pronto!

Saludos,
Leonardo

**Comment by rodrigolece** [comment]
@carranco-sga hemos estado muy al pendiente de tu repositorio. Como estoy seguro sabes, nosotros también recopilamos los datos que publica Salud [mexicovid19/Mexico-datos](https://github.com/mexicovid19/Mexico-datos) y para no seguir duplicando nuestros esfuerzos queríamos ponernos en contacto para proponerte colaborar más estrechamente.

Tenemos en mente dos puntos principales:
1. Ponernos de acuerdo sobre un formato (en el sentido más general: un estructura de archivos y de los datos agregados). Tú usas un formato, nostros otro, y hay muchas otras maneras de hacerlo (por ejemplo el repo de latinoamérica [DataScienceResearchPeru/covid-19_latinoamerica](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica), o uno muy bueno para el UK [tomwhite/covid-19-uk-data](https://github.com/tomwhite/covid-19-uk-data)). Cada formato tiene sus fortalezas y el chiste sería encontrar las mejores soluciones juntos.
2. Podemos compartir una herramienta que tenemos para jalar los datos de Salud un poco más eficientemente que hacer el scraping de los PDFs. No te podemos decir mucho más por aquí (no es nada ilegal, no te preocupes, pero no la podemos hacer pública), pero creo que es una buena solución a una parte del problema.

Nos encantaría platicar contigo si esta colaboración te interesa, y para platicarte más sobre la alternativa al scraping :)

PS: Vemos que eres digno alumno de Luis Benet y David Sanders y que programas en Julia! A algunos de nosotros también nos marcaron mucho Luis y David (todos somos de Ciencias pero no a todos nos dieron clase). Personalmente, yo me he tenido que mover a Python pero creo que esto no sería un problema para la colaboración, cualquiera de los dos lenguajes funcionaría.
